BROADLINK_CONTROLLER = "Broadlink"
XIAOMI_CONTROLLER = "Xiaomi"
MQTT_CONTROLLER = "MQTT"
LOOKIN_CONTROLLER = "LOOKin"
ESPHOME_CONTROLLER = "ESPHome"
ZHA_CONTROLLER = "ZHA"
UFOR11_CONTROLLER = "UFOR11"

ENC_BASE64 = "Base64"
ENC_HEX = "Hex"
ENC_PRONTO = "Pronto"
ENC_RAW = "Raw"

BROADLINK_COMMANDS_ENCODING = [ENC_BASE64, ENC_HEX, ENC_PRONTO]
XIAOMI_COMMANDS_ENCODING = [ENC_PRONTO, ENC_RAW]
MQTT_COMMANDS_ENCODING = [ENC_RAW]
LOOKIN_COMMANDS_ENCODING = [ENC_PRONTO, ENC_RAW]
ESPHOME_COMMANDS_ENCODING = [ENC_RAW]
ZHA_COMMANDS_ENCODING = [ENC_RAW]
UFOR11_COMMANDS_ENCODING = [ENC_RAW]

CONTROLLER_SUPPORT = {
    BROADLINK_CONTROLLER: BROADLINK_COMMANDS_ENCODING,
    XIAOMI_CONTROLLER: XIAOMI_COMMANDS_ENCODING,
    MQTT_CONTROLLER: MQTT_COMMANDS_ENCODING,
    LOOKIN_CONTROLLER: LOOKIN_COMMANDS_ENCODING,
    ESPHOME_CONTROLLER: ESPHOME_COMMANDS_ENCODING,
    ZHA_CONTROLLER: ZHA_COMMANDS_ENCODING,
    UFOR11_CONTROLLER: UFOR11_COMMANDS_ENCODING,
}
